print("My Daily Routine")
print("5:50 AM - Wake Up")
print("6:00 AM - Study Time")
print("7:00 AM - Get Ready for School")
print("7:30 AM - Breakfast")
print("8:00 AM - Bus to school")
print("8:30 AM - School")
print("3:30 PM - Dispersal")
print("4:30 PM - Reached Home")
print("5:00 PM - Maths Class")
print("6:00 PM - Watch TV")
print("7:00 PM - Maths Class")
print("8:00 PM - Dinner")
print("8:30 PM - Practice Piano")
print("9:30 PM - Piano Class")
print("10:30 PM - Study Time")
print("12:00 AM - Sleep")
study_time = (1+7+1+1+1.5)*7
print("Total Study Time in a week: ", study_time, "hours")
