name=input("Enter your name: ")
goal=input("Enter your personal goal: ")
month=input("Enter your target month: ")
practicetime=int(input("Enter your daily practice time(in minutes): "))
print("\n All information provided")
print("Name:", name)
print("Personal Goal:", goal)
print("Target Month:", month)
print("Daily Practice Time:", practicetime, "minutes")
print("\n Goal Progress! \n")
print("Goal: ", goal, end="   ")
print("Status: Not Started")
import keyword
print("\n The python keywords are: \n")
print(keyword.kwlist)